services:
  app:
    build: .
    image: pathwaylk:local
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password123
      - NEO4J_DATABASE=neo4j
      - MONGODB_URI=mongodb://admin:password123@mongo:27017
      - MONGODB_DATABASE=pathwaylk
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password123
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      # Google API Key for Gemini LLM and YouTube Data API
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Alternative key names (same key works for both services)
      - GEMINI_API_KEY=${GOOGLE_API_KEY}
      - YOUTUBE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - neo4j
      - weaviate
    restart: unless-stopped
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - neo4j_data:/data
  weaviate:
    image: semitechnologies/weaviate:1.19.7
    ports:
      - "8081:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongo_data:
  neo4j_data:
  weaviate_data:
